server:
  port: 8081

spring:
  application:
    name: client-service

logging:
  level:
    com.example.newsservice: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"